# Generated by Django 5.2.11 on 2026-02-22 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.BigIntegerField()),
                ('cedula', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('numemp', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('deptno', models.IntegerField()),
                ('correo', models.EmailField(max_length=50, null=True)),
                ('cargo', models.CharField(max_length=50)),
                ('salario', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numemp', models.IntegerField(null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('descripcion', models.CharField(blank=True, max_length=50)),
                ('categoria', models.CharField(choices=[('Comesticos', 'Comesticos'), ('Prendas', 'Prendas'), ('Calzado', 'Calzado')], max_length=50, null=True)),
                ('precio', models.FloatField(null=True)),
                ('stocki', models.IntegerField()),
                ('entradas', models.IntegerField()),
                ('salidas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('sector', models.CharField(max_length=50)),
                ('nombrecontac', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('idf', models.IntegerField(default=0)),
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En camino', 'En camino'), ('Enviado', 'Enviado')], max_length=200, null=True)),
                ('nota', models.CharField(max_length=200, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dominus.cliente')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dominus.inventario1')),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('detalle', models.CharField(choices=[('Compra', 'Compra'), ('Devolucion', 'Devolucion')], max_length=50, null=True)),
                ('debito', models.FloatField(null=True)),
                ('credito', models.FloatField(null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dominus.cliente')),
                ('idf', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Dominus.orden')),
            ],
        ),
        migrations.AddField(
            model_name='inventario1',
            name='idp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dominus.proveedor'),
        ),
        migrations.AddField(
            model_name='inventario1',
            name='tags',
            field=models.ManyToManyField(to='Dominus.tag'),
        ),
    ]
