# Generated by Django 3.1 on 2022-03-21 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dominus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='idf',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Dominus.orden', to_field='idf'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='idf',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
