# Generated by Django 3.1 on 2022-03-21 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dominus', '0002_auto_20220320_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='idf',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Dominus.orden'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='idf',
            field=models.IntegerField(default=0),
        ),
    ]
